services:
  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      SET_CONTAINER_TIMEZONE: true
      CONTAINER_TIMEZONE: Asia/Shanghai
    ports:
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ${MOUNT_WEB_ROOT}:/usr/share/nginx/html
      - ./data/share:/data/share
    depends_on:
      - php74
    restart: unless-stopped
    networks:
      - backend
      - frontend

  php74:
    image: php:7.4-fpm
    container_name: php74
    environment:
      SET_CONTAINER_TIMEZONE: true
      CONTAINER_TIMEZONE: Asia/Shanghai
    privileged: true
    build:
      context: ./php/7.4
    volumes:
      - ${MOUNT_WEB_ROOT}:/usr/share/nginx/html
      - ./php/7.4/php.ini:/usr/local/etc/php/php.ini
      - ./php/7.4/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/7.4/logs:/var/log/php
      - ./data/share:/data/share
    restart: unless-stopped
    networks:
      - backend
  
  php83:
    image: php:8.3-fpm
    container_name: php83
    environment:
      SET_CONTAINER_TIMEZONE: true
      CONTAINER_TIMEZONE: Asia/Shanghai
    privileged: true
    build:
      context: ./php/8.3
    volumes:
      - ${MOUNT_WEB_ROOT}:/usr/share/nginx/html
      - ./php/8.3/php.ini:/usr/local/etc/php/php.ini
      - ./php/8.3/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/8.3/logs:/var/log/php
      - ./data/share:/data/share
    restart: unless-stopped
    networks:
      - backend
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - ${PHPMYADMIN_HTTP_PORT}:80
    environment:
      - PMA_ARBITRARY=false
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=123456
    restart: unless-stopped
    networks:
      - backend

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      SET_CONTAINER_TIMEZONE: true
      CONTAINER_TIMEZONE: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf
    restart: unless-stopped
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    environment:
      SET_CONTAINER_TIMEZONE: true
      CONTAINER_TIMEZONE: Asia/Shanghai
    volumes:
      - ./redis/data:/data/redis
      - ./redis/logs:/var/log/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/share:/data/share
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--logfile", "/var/log/redis/redis.log" ]
    restart: unless-stopped
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      SET_CONTAINER_TIMEZONE: true
      CONTAINER_TIMEZONE: Asia/Shanghai
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/logs:/var/log/mongodb
      - ./mongo/mongod.conf:/etc/mongo/mongod.conf
    command: ["mongod", "--logpath", "/var/log/mongodb/mongod.log", "--logappend"]
    restart: unless-stopped
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
