services:
  nginx:
    image: nginx:latest
    environment:
      SET_CONTAINER_TIMEZONE: true
      CONTAINER_TIMEZONE: Asia/Shanghai
    ports:
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ${MOUNT_WEB_ROOT}:${DOCKER_WEB_ROOT}
    depends_on:
      - php74
    networks:
      - backend
      - frontend

  php74:
    image: php:7.4-fpm
    container_name: php74
    environment:
      SET_CONTAINER_TIMEZONE: true
      CONTAINER_TIMEZONE: Asia/Shanghai
    privileged: true
    build:
      context: ./php/7.4
      args:
        - EXT_GD=true
        - EXT_REDIS=true
        - EXT_GRPC=false
        - EXT_PROTOBUF=false
        - EXT_MEMCACHED=true
        - EXT_SWOOLED=true
    volumes:
      - ${MOUNT_WEB_ROOT}:${DOCKER_WEB_ROOT}
      - ./php/7.4/php.ini:/usr/local/etc/php/php.ini
      - ./php/7.4/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - backend

  php81:
    image: php:8.1-fpm
    container_name: php81
    environment:
      SET_CONTAINER_TIMEZONE: true
      CONTAINER_TIMEZONE: Asia/Shanghai
    privileged: true
    build:
      context: ./php/8.1
      args:
        - EXT_GD=true
        - EXT_REDIS=true
        - EXT_GRPC=false
        - EXT_PROTOBUF=false
        - EXT_MEMCACHED=true
        - EXT_SWOOLED=true
    volumes:
      - ${MOUNT_WEB_ROOT}:${DOCKER_WEB_ROOT}
      - ./php/8.1/php.ini:/usr/local/etc/php/php.ini
      - ./php/8.1/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - backend
  
  php83:
    image: php:8.3-fpm
    container_name: php83
    environment:
      SET_CONTAINER_TIMEZONE: true
      CONTAINER_TIMEZONE: Asia/Shanghai
    privileged: true
    build:
      context: ./php/8.3
      args:
        - EXT_GD=true
        - EXT_REDIS=true
        - EXT_GRPC=false
        - EXT_PROTOBUF=false
        - EXT_MEMCACHED=true
        - EXT_SWOOLED=true
    volumes:
      - ${MOUNT_WEB_ROOT}:${DOCKER_WEB_ROOT}
      - ./php/8.3/php.ini:/usr/local/etc/php/php.ini
      - ./php/8.3/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      SET_CONTAINER_TIMEZONE: true
      CONTAINER_TIMEZONE: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 123456
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:latest
    environment:
      SET_CONTAINER_TIMEZONE: true
      CONTAINER_TIMEZONE: Asia/Shanghai
    networks:
      - backend

  mongo:
    image: mongo:latest
    environment:
      SET_CONTAINER_TIMEZONE: true
      CONTAINER_TIMEZONE: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  mongo_data:
